### PR TITLE
Sans initial connection

### PR DESCRIPTION
**Pull request by mnelson**

### CODE REVIEW

**Comment by etherbob** [comment]
This looks like it might include a fix for #50. Is that correct?

**Comment by etherbob** [comment]
Anything I can do to help get this merge approved?

**Comment by mnelson** [comment]
I'm happy to tag as an RC but I'd like to reproduce the issues described in https://github.com/taskrabbit/makara/issues/51#issuecomment-44348479.

I haven't had the time recently.

**Comment by bramswenson** [comment]
With a very simple test application, 1 master and 2 slave setup, fundamental rake tasks like db:drop and db:create fail. I am using rails 3.2.18 and Ruby 2.1.2.  The errors seem to be related to this issue, as this branch makes them stop. I cannot speak to how other functionality is effected as I've not tested yet.

**Comment by etherbob** [comment]
Is there a particular bit of functionality you are looking to test. I'd love to help get this into a release.

**Pull request merged**
