### PR TITLE
support for custom errors

### PR DESCRIPTION
**Pull request by davidjairala**
tests are green.

Unsure wether to keep this as a separate YML file or if you'd rather have it be appended to the general DB connection config YML, can see benefits on both.

Thoughts @mnelson @evantahler ?

### CODE REVIEW

**Comment by mnelson** [comment]
I would do 1 of 2 things: 

1) make it part of the makara config. 

``` yml
# database.yml
adapter: makara_mysql2
username: root
makara:
  blacklist_duration: 5
  connections:
    - role: master
    - role: slave
  connection_error_matchers:
    - "^dude-you-blew-up/"
```

2) allow it to be configured as an initializer:

``` ruby
Makara.connection_matchers << /^dude-you-blew-up/
```

**Comment by evantahler** [comment]
I vote for option 1, @mnelson @davidjairala

**Comment by davidjairala** [comment]
kk, will do that, thanks guys.

**Comment by mnelson** [comment]
Looks good, will merge when travis reports a green build.

**Pull request merged**
